joint_map:
  1: torso_yaw
  2: j_arm2_1
  3: j_arm2_2
  4: j_arm2_3
  5: j_arm2_4
  6: j_arm2_5
  7: j_arm2_6
  8: j_arm2_7
  9: j_arm1_1
  10: j_arm1_2
  11: j_arm1_3
  12: j_arm1_4
  13: j_arm1_5
  14: j_arm1_6
  15: j_arm1_7
  16: hip_yaw_1
  17: hip_pitch_1
  18: knee_pitch_1
  28: ankle_pitch_1
  29: ankle_yaw_1
  30: j_wheel_1
  19: hip_yaw_2
  20: hip_pitch_2
  21: knee_pitch_2
  28: ankle_pitch_2
  29: ankle_yaw_2
  30: j_wheel_2
  22: hip_yaw_3
  23: hip_pitch_3
  24: knee_pitch_3
  28: ankle_pitch_3
  29: ankle_yaw_3
  30: j_wheel_3
  25: hip_yaw_4
  26: hip_pitch_4
  27: knee_pitch_4
  28: ankle_pitch_4
  29: ankle_yaw_4
  30: j_wheel_4
  53: j_ft_arm2
  99: imu_joint
