# CENTAURO config
XBotInterface:
  urdf_path: "configs/ADVR_shared/centauro/urdf/centauro.urdf"
  srdf_path: "configs/ADVR_shared/centauro/srdf/centauro.srdf"
  joint_map_path: "configs/ADVR_shared/centauro/joint_map/centauro_joint_map.yaml"

RobotInterface:
  framework_name: "ROS"

ModelInterface:
  model_type: "RBDL"
  is_model_floating_base: "true"

RobotInterfaceROS:
  subclass_name: "RobotInterfaceROS"
  path_to_shared_lib: "libRobotInterfaceROS.so"
  subclass_factory_name: "robot_interface_ros"
  control_message_type: "AdvrCommandMessage"
  jointstate_message_type: "AdvrJointStateMessage"
  ft_topic_names: []
  imu_topic_names: []

RobotInterfaceXBotRT:
  subclass_name: "RobotInterfaceXBotRT"
  path_to_shared_lib: "libRobotInterfaceXBotRT.so"
  subclass_factory_name: "robot_interface_xbot_rt"

XBotRTPlugins:
  plugins: ["HomingExample"]
  io_plugins: []

NRTPlugins:
  plugins: [] 

MasterCommunicationInterface:
  framework_name: "ROS"

CustomCmnd:
  subclass_name: "CustomCmndMessage"
  path_to_shared_lib: "libCustomCmndMessage.so"
  subclass_factory_name: "customcmnd_control_message"
  joint_service_name: "/centauro/position_controller/get_joint_names"
  command_topic_name: "/centauro/position_controller/command"

JointState:
  subclass_name: "JointStateMessage"
  path_to_shared_lib: "libJointStateMessage.so"
  subclass_factory_name: "jointstate_jointstate_message"
  joint_state_topic_name: "/centauro/joint_states"

AdvrCommandMessage:
  subclass_name: "CommandAdvr"
  path_to_shared_lib: "libAdvrCommandMessage.so"
  subclass_factory_name: "advrcommandmessage_control_message"
  joint_service_name: "/centauro/position_controller/get_joint_names"
  command_topic_name: "/xbotcore/centauro/command"

AdvrJointStateMessage:
  subclass_name: "AdvrJointState"
  path_to_shared_lib: "libAdvrJointStateMessage.so"
  subclass_factory_name: "advrjointstate_jointstate_message"
  joint_state_topic_name: "/xbotcore/centauro/joint_states"

RobotInterfaceDUMMY:
  subclass_name: "RobotInterfaceDUMMY"
  path_to_shared_lib: "libRobotInterfaceDUMMY.so"
  subclass_factory_name: "robot_interface_dummy"

ModelInterfaceRBDL:
  subclass_name: "ModelInterfaceRBDL"
  path_to_shared_lib: "libModelInterfaceRBDL.so"
  subclass_factory_name: "model_interface_rbdl"

GazeboXBotPlugin:
  gains:
    j_arm1_1: {p: 5000, d: 30}
    j_arm1_2: {p: 8000, d: 50}
    j_arm1_3: {p: 5000, d: 30}
    j_arm1_4: {p: 5000, d: 30}
    j_arm1_6: {p: 2000, d: 5}
    j_arm2_1: {p: 5000, d: 30}
    j_arm2_2: {p: 8000, d: 50}
    j_arm2_3: {p: 5000, d: 30}
    j_arm2_4: {p: 5000, d: 30}
    j_arm2_6: {p: 2000, d: 5}
    torso_yaw: {p: 5000, d: 30}

x_bot_ecat:
  name: XBotCore
  sdo_xddp_prefix :
  # periodic - priority if needed here


#
ec_board_ctrl:
  eth_iface: rteth0
  #eth_iface: eth1
  #sync_cycle_time_ns: 500000
  sync_cycle_time_ns: 1000000
  #sync_cycle_time_ns: 2000000
  #sync_cycle_time_ns: 5000000
  #sync_cycle_time_ns: 10000000
  #sync_cycle_time_ns: 0
  sync_cycle_offset_ns: 1000000000
  power_off_boards: false

#
ec_boards_base:
  create_pipes: false

firmware_update:
  #
  fw_path: ../examples/fw_update/fw_test/
  #slave_pos_list: [7]
  #slave_rId_list: [7]
  # all esc
  #slave_pos_list: [0]
  # all BigMotor
  #slave_pos_list: [-1]
  # all MedMotor
  #slave_pos_list: [-2]
  # all LowPower motor
  #slave_pos_list: [-3]
  # all CentAC motor
  slave_pos_list: [-4]
  #slave_pos_list: [1]

  cent_AC:
    m3:
      bin_file: cent_AC_m3.bin
      passwd: 0xA550
    c28:
      bin_file: cent_AC_c28.bin
      passwd: 0xDAD0

#############################
# GENERIC ESC config
#############################

LpESC_X:
  control_mode: pos_3b
  sign: 1
  pos_offset: 0
  max_current_A: 6.0
  pid :
    position: [100000.0 , 0.0 , 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 3.0, 1.0, 0.001, 0.0]

HpESC_X:
  sign: 1
  pos_offset: 0

CentAcESC_X:
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [220.0 , 0.0 , 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [0.0, 0.0, 1.0, 0.002, 0.0]

  
  
  
#############################
# waist
#############################

CentAcESC_1:
  control_mode: impedance_d4
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position:   [180.0 , 0.0 , 1.0]
    # pos_Kp pos_Kd tor_Kp tor_Kd tor_Ki
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 1.0, 5.0, 0.002, 1.0]


##############################
# Right Arm

CentAcESC_2:
  control_mode: impedance_d4
  sign: 1
  pos_offset: 45
  max_current_A: 15.0
  pid :
    position: [150.0 , 0.0 , 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 1.0, 5.5, 0.002, 1.0]

CentAcESC_3:
  control_mode: impedance_d4
  sign: 1
  pos_offset: 45
  max_current_A: 15.0
  pid :
    position: [150.0 , 0.0 , 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 1.0, 5.0, 0.002, 1.0]

CentAcESC_4:
  control_mode: impedance_d4
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [150.0 , 0.0 , 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 1.0, 5.0, 0.002, 1.0]

CentAcESC_5:
  control_mode: impedance_d4
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [150.0 , 0.0 , 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 1.0, 5.0, 0.002, 1.0]

CentAcESC_6:
  control_mode: pos_3b
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [150.0 , 0.0 , 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [200.0, 3.0, 5.0, 0.002, 0.0]

CentAcESC_7:
  control_mode: pos_3b
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [150.0 , 0.0 , 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [200.0, 3.0, 5.0, 0.002, 0.0]

CentAcESC_8:
  control_mode: pos_3b
  sign: 1
  pos_offset: 0
  max_current_A: 6.0
  pid :
    position: [150.0 , 0.0 , 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [200.0, 3.0, 5.0, 0.002, 0.0]

##############################
# Left Arm

CentAcESC_9:
  control_mode: impedance_d4
  sign: 1
  pos_offset: -45
  max_current_A: 15.0
  pid :
    position: [150.0 , 0.0 , 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 1.0, 5.0, 0.003, 1.0]

CentAcESC_10:
  control_mode: impedance_d4
  sign: 1
  pos_offset: -45
  max_current_A: 15.0
  pid :
    position: [150.0 , 0.0 , 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 1.0, 5.0, 0.003, 1.0]

CentAcESC_11:
  control_mode: impedance_d4
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [150.0 , 0.0 , 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 1.0, 5.0, 0.003, 1.0]

CentAcESC_12:
  control_mode: impedance_d4
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [150.0 , 0.0 , 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 1.0, 5.0, 0.003, 1.0]

CentAcESC_13:
  control_mode: pos_3b
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [150.0 , 0.0 , 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 3.0, 1.0, 0.001, 0.0]

CentAcESC_14:
  control_mode: pos_3b
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [150.0 , 0.0 , 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 3.0, 1.0, 0.001, 0.0]

CentAcESC_15:
  control_mode: pos_3b
  sign: 1
  pos_offset: 0
  max_current_A: 6.0
  pid :
    position: [150.0 , 0.0 , 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 3.0, 1.0, 0.001, 0.0]
    
##############################
# FrontLeft Leg
    
CentAcESC_71:
  control_mode: impedance_d4
  sign: 1
  pos_offset: 45
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [500.0, 10.0, 6.0, 0.002, 1.0]

CentAcESC_72:
  control_mode: impedance_d4
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [500.0, 10.0, 6.0, 0.002, 1.0]

CentAcESC_73:
  control_mode: impedance_d4
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [500.0, 10.0, 6.0, 0.003, 1.0]

CentAcESC_74:
  control_mode: impedance_d4
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [500.0, 10.0, 6.0, 0.002, 1.0]

CentAcESC_75:
  control_mode: impedance_d4
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [500.0, 10.0, 6.0, 0.002, 1.0]

CentAcESC_76:
  control_mode: vel_71
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [10.0 , 0.0 , 0.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [10.0, 0.0, 0.0, 0.0, 0.0]


##############################
# FrontRight Leg
    
CentAcESC_41:
  control_mode: impedance_d4
  sign: 1
  pos_offset: -45
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [500.0, 10.0, 6.0, 0.002, 1.0]

CentAcESC_42:
  control_mode: impedance_d4
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [500.0, 10.0, 6.0, 0.002, 1.0]

CentAcESC_43:
  control_mode: impedance_d4
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [500.0, 10.0, 6.0, 0.002, 1.0]

CentAcESC_44:
  control_mode: impedance_d4
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [500.0, 10.0, 6.0, 0.002, 1.0]

CentAcESC_45:
  control_mode: impedance_d4
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [500.0, 10.0, 6.0, 0.002, 1.0]

CentAcESC_46:
  control_mode: vel_71
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [10.0 , 0.0 , 0.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [10.0, 0.0, 0.0, 0.0, 0.0]


##############################
# HindLeft Leg
    
CentAcESC_61:
  control_mode: impedance_d4
  sign: 1
  pos_offset: -45
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [500.0, 10.0, 6.0, 0.002, 1.0]

CentAcESC_62:
  control_mode: impedance_d4
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [500.0, 10.0, 6.0, 0.002, 1.0]

CentAcESC_63:
  control_mode: impedance_d4
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [500.0, 10.0, 6.0, 0.002, 1.0]

CentAcESC_64:
  control_mode: impedance_d4
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [500.0, 10.0, 6.0, 0.002, 1.0]

CentAcESC_65:
  control_mode: impedance_d4
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [500.0, 10.0, 5.5, 0.005, 1.0]
    
CentAcESC_66:
  control_mode: vel_71
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [10.0 , 0.0 , 0.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [10.0, 0.0, 0.0, 0.0, 0.0]

    
##############################
# HindRight Leg

CentAcESC_51:
  control_mode: impedance_d4
  sign: 1
  pos_offset: 45
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [500.0, 10.0, 5.5, 0.003, 1.0]

CentAcESC_52:
  control_mode: impedance_d4
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [500.0, 10.0, 6.0, 0.002, 1.0]

CentAcESC_53:
  control_mode: impedance_d4
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [500.0, 10.0, 6.0, 0.002, 1.0]

CentAcESC_54:
  control_mode: impedance_d4
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [500.0, 10.0, 6.0, 0.002, 1.0]

CentAcESC_55:
  control_mode: impedance_d4
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [500.0, 10.0, 6.0, 0.002, 1.0]

CentAcESC_56:
  control_mode: vel_71
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [10.0 , 0.0 , 0.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [10.0, 0.0, 0.0, 0.0, 0.0] 

